version: '3.7'
services:
    casdemo:
        image: docprod.pvt.hawaii.edu/casdemo/casdemo:SNAPSHOT
        build:
            context: ../
            dockerfile: docker/Dockerfile
        networks:
            - proxy
        environment:
            SPRING_APPLICATION_JSON: >
                {
                    "spring.profiles.active": "test"
                }
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.casdemo-router.rule=PathPrefix(`/casdemo`)"
                - "traefik.http.routers.casdemo-router.middlewares=casdemo-middleware1"
                - "traefik.http.middlewares.casdemo-middleware1.headers.customrequestheaders.X-Forwarded-Host=www.test.hawaii.edu"
                - "traefik.http.middlewares.casdemo-middleware1.headers.customrequestheaders.X-Forwarded-Proto=https"
                - "traefik.http.middlewares.casdemo-middleware1.headers.customrequestheaders.X-Forwarded-Port=443"
                - "traefik.http.middlewares.casdemo-middleware1.headers.customrequestheaders.X-Debug-Traefik=middleware-applied"
                - "traefik.http.routers.casdemo-router.service=casdemo-service"
                - "traefik.http.services.casdemo-service.loadbalancer.server.port=8080"

networks:
    proxy:
        external: true
