name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test-with-maven:
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                java: [ '23' ]
        runs-on: ${{ matrix.os }}
        name: Running Java ${{ matrix.java }} on ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v2
                with:
                    distribution: temurin
                    java-version: ${{ matrix.java }}
            -   name: Test code
                run: ./mvnw -B -q test -D'logging.level.edu.hawaii.its.casdemo=OFF' -D'logging.level.org.springframework=ERROR' -D'spring.main.banner-mode=off'
    test-with-gradle:
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                java: [ '23' ]
        runs-on: ${{ matrix.os }}
        name: Running Java ${{ matrix.java }} on ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v2
                with:
                    distribution: temurin
                    java-version: ${{ matrix.java }}
            -   name: Test code
                run: ./gradlew test
